version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=projectNotifyDB
      - POSTGRES_USER=wwen
      - POSTGRES_PASSWORD=test
  redis:
    image: "redis:alpine"
  web:
    build: .
#    image: weswwn/project-notify:1.1
#    volumes:
    command: gunicorn --log-level debug --error-logfile - --access-logfile - --bind 0.0.0.0:8080 projectNotifyv2_be.wsgi
    #      - .:/code
#    ports:
#      - "80:8080"
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  celery:
    build: .
#    image: weswwn/project-notify:1.1
    command: celery -A projectNotifyv2_be worker -l info
#    volumes:
#      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
#    image: weswwn/project-notify:1.1
    environment:
      - POSTGRES_DB=projectNotifyDB
      - POSTGRES_USER=wwen
      - POSTGRES_PASSWORD=test
    command: bash -c "python3 manage.py migrate && celery -A projectNotifyv2_be beat -l info --pidfile= --scheduler django_celery_beat.schedulers:DatabaseScheduler"
#    volumes:
#      - .:/code
    depends_on:
      - db
      - redis