# Generated by Django 3.0.7 on 2020-07-06 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('course', '0002_usercourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(through='course.UserCourses', to='user.User'),
        ),
    ]
