# Generated by Django 3.0.7 on 2020-07-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200706_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='sectionNumber',
            new_name='section_number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='subjectCode',
            new_name='subject_code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='subjectNumber',
            new_name='subject_number',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject_code', 'subject_number', 'section_number')},
        ),
    ]
