# Generated by Django 3.0.7 on 2020-08-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200706_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourses',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercourses',
            name='text_sent',
            field=models.BooleanField(default=False),
        ),
    ]
