# Generated by Django 3.0.7 on 2020-08-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200804_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourses',
            name='sms_message_sid',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
