# Generated by Django 3.0.7 on 2020-07-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_usercourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=10)),
                ('courses', models.ManyToManyField(through='course.UserCourses', to='course.Course')),
            ],
        ),
    ]
